src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $username;

    /**
     * @ORM\OneToMany(targetEntity=ChatPost::class, mappedBy="user", orphanRemoval=true)
     */
    private $chatPosts;

    /**
     * @ORM\OneToMany(targetEntity=Trick::class, mappedBy="author")
     */
    private $tricks;

    /**
     * @ORM\OneToMany(targetEntity=Trick::class, mappedBy="updatedBy")
     */
    private $tricksUpdate;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $avatarFilename;

    public function __construct()
    {
        $this->chatPosts = new ArrayCollection();
        $this->tricks = new ArrayCollection();
        $this->tricksUpdate = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
//        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @return Collection|ChatPost[]
     */
    public function getChatPosts(): Collection
    {
        return $this->chatPosts;
    }

    public function addChatPost(ChatPost $chatPost): self
    {
        if (!$this->chatPosts->contains($chatPost)) {
            $this->chatPosts[] = $chatPost;
            $chatPost->setUser($this);
        }

        return $this;
    }

    public function removeChatPost(ChatPost $chatPost): self
    {
        if ($this->chatPosts->contains($chatPost)) {
            $this->chatPosts->removeElement($chatPost);
            // set the owning side to null (unless already changed)
            if ($chatPost->getUser() === $this) {
                $chatPost->setUser(null);
            }
        }

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->username);
    }

    /**
     * @return Collection|Trick[]
     */
    public function getTricks(): Collection
    {
        return $this->tricks;
    }

    public function addTrick(Trick $trick): self
    {
        if (!$this->tricks->contains($trick)) {
            $this->tricks[] = $trick;
            $trick->setAuthor($this);
        }

        return $this;
    }

    public function removeTrick(Trick $trick): self
    {
        if ($this->tricks->contains($trick)) {
            $this->tricks->removeElement($trick);
            // set the owning side to null (unless already changed)
            if ($trick->getAuthor() === $this) {
                $trick->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Trick[]
     */
    public function getTricksUpdate(): Collection
    {
        return $this->tricksUpdate;
    }

    public function addTricksUpdate(Trick $tricksUpdate): self
    {
        if (!$this->tricksUpdate->contains($tricksUpdate)) {
            $this->tricksUpdate[] = $tricksUpdate;
            $tricksUpdate->setUpdatedBy($this);
        }

        return $this;
    }

    public function removeTricksUpdate(Trick $tricksUpdate): self
    {
        if ($this->tricksUpdate->contains($tricksUpdate)) {
            $this->tricksUpdate->removeElement($tricksUpdate);
            // set the owning side to null (unless already changed)
            if ($tricksUpdate->getUpdatedBy() === $this) {
                $tricksUpdate->setUpdatedBy(null);
            }
        }

        return $this;
    }

    public function getAvatarFilename(): ?string
    {
        return $this->avatarFilename;
    }

    public function setAvatarFilename(?string $avatarFilename): self
    {
        $this->avatarFilename = $avatarFilename;

        return $this;
    }
}

templates/_partials/_ajax-loader.html.twig
<div class="d-none" id="loader">
    <div class="lds-roller">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>

templates/_partials/_categories-list.html.twig
<ul class="custom-list dynamic-bullets">
	{% if categories|length > 0 %}
		{% for category in categories %}
			<li class="custom-list-item{% if current_menu is defined and current_menu == "category.show." ~ category.slug %} active{% endif %}">
				<a class=""
				   href="{{ path("category.show", {id: category.id, slug:category.slug}) }}">{{ category.title }}</a>
			</li>
		{% endfor %}
		<li class="custom-list-item{% if current_menu is defined and current_menu == "trick.index" %} active{% endif %}">
			<a class="font-weight-normal"
			   href="{{ path("trick.index") }}"><b>Tous les tricks</b></a>
		</li>
	
	
	{% else %}
		<li class="custom-list-item{% if current_menu is defined and current_menu == "trick.index" %} active{% endif %}">
			<a class="font-weight-normal"
			   href="{{ path("trick.index") }}">Les tricks</a>
		</li>
	{% endif %}
</ul>

templates/_partials/_chatpost.html.twig
<div class="card mb-2 chat-message{% if app.user.id is defined and post.user.id == app.user.id %} is-mine{% endif %}">
    <div class="card-body">
        <div class="row align-items-center">
            <div class="col-4 d-none d-md-block">
                <div class="avatar small">
                    {% if post.user.avatarFilename %}
                        <img class="img-fluid" src="{{ asset(getUploadedImage("avatars", post.user.avatarFilename)) }}"
                             alt="{{ post.user.username }} avatar">
                    {% else %}
                        <img class="img-fluid" src="{{ asset(getImage("no-avatar.png")) }}"
                             alt="{{ post.user.username }} avatar">
                    {% endif %}
                </div>
            </div>
            <div class="col-30 col-md-26">
                <div class="row">
                    <div class="{% if is_granted("DELETE", post) %}col-23{% else %}col-30{% endif %} text-bold">
                        Ecrit par {{ post.user.username }} le {{ post.dateadd|date('l d F Y') }}
                    </div>
                    {% if is_granted("DELETE", post) %}
                        <div class="col-7">
                            <form method="post" class="d-inline-block"
                                  action="{{ path("chatpost.delete", {trickSlug:trick.slug, trickID: trick.id, id: post.id}) }}"
                                  onsubmit="return confirm('Êtes vous sur de vouloir supprimer ce message?')">
                                <input type="hidden" name="_method" value="DELETE">
                                <input type="hidden" name="_token" value="{{ csrf_token("delete" ~ post.id) }}">
                                <button type="submit" href="#" class="btn btn-danger btn-sm mx-3">
                                    <span class="fa fa-trash"></span>
                                </button>
                            </form>
                        </div>
                    {% endif %}
                </div>
                <div class="mt-2 pr-3 font-weight-light">
                    {{ post.message }}
                </div>
            </div>
        </div>
    </div>
</div>

templates/_partials/_chatposts-listing.html.twig
{% for post in chatposts %}
    {% include "_partials/_chatpost.html.twig" %}
{% endfor %}

templates/_partials/_footer.html.twig
<div class="container">
	<div class="row">
		<div class="col-30 col-lg-10 mb-5 mb-lg-0 d-flex flex-column justify-content-center text-center text-lg-left">
			<h2 class="text-uppercase">Snowtricks</h2>
			<small>Study project for <a class="text-underline" target="_blank" href="https://openclassrooms.com">Openclassrooms</a>
				<br>by <a class="text-underline"
						  target="_blank" href="https://tristan-florin.fr">Tristan Florin</a></small>
			<div class="social-networks mt-3">
				<a target="_blank" href="https://facebook.com/tristan.florin" class="btn btn-outline-light mr-2" href="#"><span class="fa fa-facebook"></span></a>
				<a target="_blank" class="btn btn-outline-light mr-2" href="https://linkedin.com/in/tristan-florin"><span class="fa fa-linkedin"></span></a>
			</div>
		</div>
		
		<div class="col-30 col-md-15 col-lg-10 mb-5 mb-lg-0 text-center text-md-left">
			<h5 class="text-uppercase border-bottom d-inline-block pr-md-5 pb-2">Catégories :</h5>
			{% if current_menu is defined %}
				{{ render(controller("App\\Controller\\CategoryController::CategoryList", {currentMenu: current_menu})) }}
			{% else %}
				{{ render(controller("App\\Controller\\CategoryController::CategoryList")) }}
			{% endif %}
		</div>
		
		<div class="col-30 col-md-15 col-lg-10 text-center text-md-left">
			<h5 class="text-uppercase border-bottom d-inline-block pr-md-5 pb-2">Dashboard :</h5>
			<ul class="custom-list">
				<li class="custom-list-item{% if current_menu is defined and current_menu == "manage.trick.new" %} active{% endif %}">
					<a href="{{ path("manage.trick.new") }}"><span class="fa fa-plus"></span> Nouveau Trick</a>
				</li>
				<li class="custom-list-item{% if current_menu is defined and current_menu == "manage.trick.index" %} active{% endif %}">
					<a href="{{ path("manage.trick.index") }}"><span class="fa fa-user"></span> Gérer des Tricks</a>
				</li>
				
				<li class="custom-list-item{% if current_menu is defined and current_menu == "manage.category.new" %} active{% endif %}">
					<a href="{{ path("manage.category.index") }}"><span class="fa fa-object-group"></span> Gérer les
						catégories</a>
				</li>
				{% if app.user.username is defined %}
					<li class="custom-list-item">
						<a href="{{ path("user.show") }}"><span class="fa fa-user"></span> {{ app.user.username }}</a>
					</li>
					<li class="custom-list-item">
						<a href="{{ path("app_logout") }}"><span class="fa fa-sign-out"></span> Logout</a>
					</li>
				{% else %}
					<li class="custom-list-item{% if current_menu is defined and current_menu == "app_login" %} active{% endif %}">
						<a href="{{ path("app_login") }}"><span class="fa fa-sign-in"></span> Se connecter</a>
					</li>
					<li class="custom-list-item{% if current_menu is defined and current_menu == "app_register" %} active{% endif %}">
						<a href="{{ path("app_register") }}"><span class="fa fa-user-plus"></span> S'inscrire</a>
					</li>
				{% endif %}
			</ul>
		</div>
	</div>
</div>

templates/_partials/_listing-page-header.html.twig
{% if is_home_page is defined and is_home_page %}
	{% set home = true %}
{% else %}
	{% set home = false %}
{% endif %}
<div class="{% if home %}home-jumbotron {% endif %}bg-white jumbotron jumbotron-fluid">
	{% if home %}
		<h1 class="jumbotron-title text-center text-uppercase text-primary">Snowtricks</h1>
		<p class="lead text-center text-bold">La communauté francophone dédiée au Snowboard</p>
	{% elseif category is defined %}
		<div class="container-fluid px-0">
			<div class="row mx-0">
				<div class="category-img-container px-0 col-30 col-lg-15">
					<img src="{{ asset(getImage("cat-img.jpg")) }}" alt="" class="img-fluid">
				</div>
				<div class="px-5 col-30 col-lg-15 d-flex flex-column justify-content-center py-5">
					<h1 class="jumbotron-title text-uppercase text-primary">{{ category.title }}</h1>
					<p class="lead pb-3 border-bottom">{{ category.description }}</p>
				</div>
			</div>
		</div>
	{% else %}
		<h1 class="jumbotron-title text-center text-uppercase text-primary">Tous les tricks</h1>
	{% endif %}
</div>

templates/_partials/_listing.html.twig
{% for trick in tricks %}
    {% include "_partials/_trick-miniature.html.twig" %}
{% endfor %}

templates/_partials/_messages.html.twig
<div class="messages">
    {% for message in app.flashes("success") %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

    {% for message in app.flashes("warning") %}
        <div class="alert alert-error">
            {{ message }}
        </div>
    {% endfor %}

    {% for message in app.flashes("error") %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}

    {% if errors is defined %}
        {% for error in errors %}
            <div class="alert alert-danger">
                {{ error.message }}
            </div>
        {% endfor %}
    {% endif %}
</div>

templates/_partials/_nav.html.twig
{% block nav %}
    <div class="container">
        <a class="navbar-brand text-bold" href="/">S.T.</a>
        <button class="navbar-toggler hamburger hamburger--spin" type="button" data-toggle="collapse"
                data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="hamburger-box">
                <span class="hamburger-inner"></span>
              </span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item{% if current_menu is defined and current_menu == "home" %} active{% endif %}">
                    <a class="nav-link" href="{{ path("home") }}">Home</a>
                </li>
                {% if current_menu is defined %}
                    {{ render(controller("App\\Controller\\CategoryController::navbarDropdownList", {currentMenu: current_menu})) }}
                {% else %}
                    {{ render(controller("App\\Controller\\CategoryController::navbarDropdownList")) }}
                {% endif %}
            </ul>
            <ul class="navbar-nav right-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="fa fa-edit"></span><span class="d-inline d-lg-none ml-2">Dashboard</span>
                    </a>
                    <div class="dropdown-menu user-dropdown" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item{% if current_menu is defined and current_menu == "manage.trick.index" %} active{% endif %}"
                           href="{{ path("manage.trick.index") }}"><span class="fa fa-user"></span> Gérer des Tricks</a>
                        <a class="dropdown-item{% if current_menu is defined and current_menu == "manage.trick.new" %} active{% endif %}"
                           href="{{ path("manage.trick.new") }}"><span class="fa fa-plus"></span> Nouveau Trick</a>
                        <a class="dropdown-item{% if current_menu is defined and current_menu == "manage.category.new" %} active{% endif %}"
                           href="{{ path("manage.category.index") }}"><span class="fa fa-object-group"></span> Gérer
                            les
                            catégories</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="fa fa-user"></span><span class="d-inline d-lg-none ml-2">Utilisateur</span>
                    </a>
                    <div class="dropdown-menu user-dropdown" aria-labelledby="navbarDropdown">
                        {% if app.user.username is defined %}
                            <a class="dropdown-item" href="{{ path("user.show") }}"><span
                                        class="fa fa-user"></span> {{ app.user.username }}
                            </a>
                            <a class="dropdown-item" href="{{ path("app_logout") }}"><span
                                        class="fa fa-sign-out"></span> Logout</a>
                        {% else %}
                            <a class="dropdown-item{% if current_menu is defined and current_menu == "app_login" %} active{% endif %}"
                               href="{{ path("app_login") }}"><span class="fa fa-sign-in"></span> Se connecter</a>
                            <a class="dropdown-item{% if current_menu is defined and current_menu == "app_register" %} active{% endif %}"
                               href="{{ path("app_register") }}"><span class="fa fa-user-plus"></span>
                                S'inscrire</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

templates/_partials/_trick-miniature.html.twig
<div class="col-30 col-sm-15 col-lg-10 col-xl-6 my-3 transition-200">
	<div class="card dynamic-card">
		<div class="img-container">
			{% if trick.pictures|length > 0 %}
				<img class="card-img-top"
					 src="{{ asset(getUploadedImage("tricks", trick.pictures|first.filename, true)) }}"
					 alt="{{ trick.title }}_cover">
			{% endif %}
			<div class="img-overlayer"></div>
		</div>
		<div class="card-hidden-section">
			{% if is_granted("EDIT", trick) or is_granted("DELETE", trick) %}
				<div class="actions">
					{% if is_granted("EDIT", trick) %}
						<a href="{{ path("manage.trick.edit", {id: trick.id, slug: trick.slug}) }}"
						   class="btn pb-0 text-light"> <span class="fa fa-edit"></span> </a>
					{% endif %}
					{% if is_granted("DELETE", trick) %}
						<form method="post" class="d-inline-block"
							  action="{{ path("manage.trick.delete", {id: trick.id}) }}"
							  onsubmit="return confirm('Êtes vous sur de vouloir supprimer ce trick?')">
							<input type="hidden" name="_method" value="DELETE"> <input type="hidden" name="_token"
																					   value="{{ csrf_token("delete" ~ trick.id) }}">
							<button type="submit" href="#" class="btn text-danger pb-0">
								<span class="fa fa-trash"></span>
							</button>
						</form>
					{% endif %}
				</div>
			{% endif %}
			
			<a class="btn btn-outline-primary card-overlayer-link"
			   href="{{ path("trick.show", {id:trick.id, slug:trick.slug}) }}">Voir le trick</a>
			
			{% if trick.categories|length > 0 %}
				<div class="py-1 card-categories text-center">
					{% for cat in trick.categories %}
						<small>
							{% if category is defined and category != null and category.id == cat.id %}
								<span>{{ cat.title }}</span>
							{% else %}
								<a href="{{ path('category.show', {id: cat.id, slug: cat.slug}) }}">{{ cat.title }}</a>
							{% endif %}
							{% if not loop.last %} |{% endif %}
						</small>
					{% endfor %}
				</div>
			{% endif %}
		</div>
		
		<div class="card-body">
			<div class="card-header">
				<h5 class="card-title">
					{{ trick.title|u.truncate(40, "...") }}
				</h5>
			</div>
			<div class="card-body-content">
				<p class="card-very-small mb-2 text-primary text-center">
					{% for i in 1..trick.difficulty %}
						<small class="fa fa-snowflake-o"> </small>
					{% endfor %}
				</p>
				<p class="card-text">{{ trick.description|u.truncate(40, "...") }}</p>
				<p class="card-small text-muted mb-1">
					{% if trick.updatedBy is not null %}
						<small class="d-block text-muted"> Dernière mise a jour par {{ trick.updatedBy.username }}
							le {{ trick.dateupdate|format_datetime('full', 'none', locale='fr') }}
						</small>
					{% else %}
						<small class="d-block text-muted"> Ajouté par {{ trick.author.username }}
							le {{ trick.dateadd|format_datetime('full', 'none', locale='fr') }}
						</small>
					{% endif %}
				</p>
			</div>
		</div>
	</div>
</div>

templates/_partials/_trick-slider.html.twig
{% if trick.pictures|length > 0 %}
    <div class="mx-auto mb-4 mb-xl-0" style="max-width: 1200px;">
        <!-- Slider main container -->
        <div class="trick-show-images js-trick-show-images-swiper overflow-hidden">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">
                <!-- Slides -->
                {% for picture in trick.pictures %}
                    <div class="swiper-slide d-flex justify-content-center">
                        <img class="img-fluid" src="{{ asset(getUploadedImage("tricks", picture.filename)) }}">
                    </div>
                {% endfor %}
                {% for video in trick.videos %}
                    <div class="swiper-slide d-flex justify-content-center">
                        <div class="codegena">
                            <iframe width='1280' height='720'
                                    src="https://www.youtube.com/embed/{{ video.youtubeId }}?&theme=dark&autoplay=0&autohide=2&modestbranding=1&fs=0"
                                    frameborder="0">
                            </iframe>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <!-- If we need pagination -->
            {#            <div class="slider-center-buttons">#}
            {#                <button class="m-3 btn btn-outline-primary swiper-button-prev round-btn">#}
            {#                    <span class="fa fa-angle-left"></span>#}
            {#                </button>#}
            {#                <button class="m-3 btn btn-outline-primary swiper-button-next round-btn">#}
            {#                    <span class="fa fa-angle-right"></span>#}
            {#                </button>#}
            {#            </div>#}
        </div>

        <div class="mt-2 trick-show-images-thumbs js-trick-show-images-swiper-thumbs overflow-hidden">
            <!-- Additional required wrapper -->
            <div class="swiper-wrapper">
                <!-- Slides -->
                {% for picture in trick.pictures %}
                    <div class="swiper-slide d-flex justify-content-center">
                        <img class="img-fluid"
                             src="{{ asset(getUploadedImage("tricks", picture.filename, true)) }}">
                        <div class="overlayer"></div>
                    </div>
                {% endfor %}
                {% for video in trick.videos %}
                    <div class="swiper-slide d-flex justify-content-center position-relative">
                        <img class="img-fluid"
                             src="http://img.youtube.com/vi/{{ video.youtubeId }}/sddefault.jpg">
                        <div class="youtube-thumb-logo">
                            <span class="fa fa-youtube-play"></span>
                        </div>
                        <div class="overlayer"></div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endif %}

templates/_partials/messages.html.twig
<div class="messages">
    {% for message in app.flashes("success") %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

    {% for message in app.flashes("warning") %}
        <div class="alert alert-error">
            {{ message }}
        </div>
    {% endfor %}

    {% for message in app.flashes("error") %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}
</div>

templates/_partials/nav.html.twig
{% block nav %}
    <nav class="main-navbar navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">SnowTricks</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item{% if current_menu is defined and current_menu == "home" %} active{% endif %}">
                    <a class="nav-link" href="{{ path("home") }}">Home</a>
                </li>
                <li class="nav-item{% if current_menu is defined and current_menu == "tricks_list" %} active{% endif %}">
                    <a class="nav-link" href="{{ path("trick.index") }}">Tricks</a>
                </li>
            </ul>
            <ul class="navbar-nav right-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="fa fa-edit"></span>
                    </a>
                    <div class="dropdown-menu user-dropdown" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item{% if current_menu is defined and current_menu == "admin.trick.index" %} active{% endif %}"
                           href="{{ path("admin.trick.index") }}"><span class="fa fa-user"></span> Gérer des Tricks</a>
                        <a class="dropdown-item{% if current_menu is defined and current_menu == "admin.trick.new" %} active{% endif %}"
                           href="{{ path("admin.trick.new") }}"><span class="fa fa-plus"></span> Nouveau Trick</a>
                        <a class="dropdown-item{% if current_menu is defined and current_menu == "admin.category.new" %} active{% endif %}"
                           href="{{ path("admin.category.index") }}"><span class="fa fa-object-group"></span> Gérer les catégories</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="fa fa-user"></span>
                    </a>
                    <div class="dropdown-menu user-dropdown" aria-labelledby="navbarDropdown">
                        {% if app.user.username is defined %}
                            <a class="dropdown-item" href="#"><span class="fa fa-user"></span> {{ app.user.username }}</a>
                            <a class="dropdown-item" href="{{ path("app_logout") }}"><span class="fa fa-sign-out"></span> Logout</a>
                        {% else %}
                            <a class="dropdown-item{% if current_menu is defined and current_menu == "app_login" %} active{% endif %}" href="{{ path("app_login") }}"><span class="fa fa-sign-in"></span> Se connecter</a>
                            <a class="dropdown-item{% if current_menu is defined and current_menu == "app_register" %} active{% endif %}" href="{{ path("app_register") }}"><span class="fa fa-user-plus"></span> S'inscrire</a>
                        {% endif %}
                    </div>
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

templates/_partials/page-header.html.twig
<div class="container">
    <h1>{{ page.title }}</h1>
</div>